{{- $root := . -}}
{{- if .Values.config.enabled }}
{{- /* create per-file ConfigMaps */ -}}
{{- range $file := $root.Values.config.files }}
  {{- $fname := $file.name }}
  {{- $san := regexReplaceAll "[^a-zA-Z0-9-]" $fname "-" }}
  {{- $cmname := printf "%s-%s" (include "mychart.fullname" $root) $san | lower }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cmname }}
  labels:
    {{- include "mychart.labels" $root | nindent 4 }}
data:
  {{ $fname }}: |
{{ ( $root.Files.Get (printf "files/config/%s" $fname) ) | indent 4 }}
---
{{- end }}

{{- /* optional default inline data configmap */ -}}
{{- if $root.Values.config.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" $root }}-default
  labels:
    {{- include "mychart.labels" $root | nindent 4 }}
data:
{{ toYaml $root.Values.config.data | indent 2 }}
{{- end }}
{{- end }}
