{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "mychart.fullname" . }}-vs
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  hosts:
    {{- range .Values.istio.hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    - {{ .Values.istio.gateway }}
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: {{ include "mychart.fullname" . }}
            port:
              number: {{ .Values.service.port }}
      retries:
        attempts: {{ .Values.istio.retries }}
        perTryTimeout: 2s
        retryOn: 5xx,reset,connect-failure,refused-stream
{{- end }}
