{{- $root := . -}}
{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "mychart.fullname" $root }}-rollout
  labels:
    {{- include "mychart.labels" $root | nindent 4 }}
spec:
  replicas: {{ $root.Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mychart.selectorLabels" $root | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mychart.selectorLabels" $root | nindent 8 }}
    spec:
      containers:
        - name: {{ include "mychart.name" $root }}
          image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          ports:
            - containerPort: {{ $root.Values.service.targetPort }}

          {{- if $root.Values.resources }}
          resources:
            {{- toYaml $root.Values.resources | nindent 12 }}
          {{- end }}

          {{- with $root.Values.probes.readiness }}
          {{- if and .enabled .path }}
          readinessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ $root.Values.service.targetPort }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- end }}

          {{- with $root.Values.probes.liveness }}
          {{- if and .enabled .path }}
          livenessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ $root.Values.service.targetPort }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- end }}

          {{- if or $root.Values.env $root.Values.ENCRYPTED_env }}
          env:
            {{- if $root.Values.env }}
            {{- toYaml $root.Values.env | nindent 12 }}
            {{- end }}
            {{- if $root.Values.ENCRYPTED_env }}
            {{- toYaml $root.Values.ENCRYPTED_env | nindent 12 }}
            {{- end }}
          {{- end }}

          {{- if or (and $root.Values.config.enabled $root.Values.config.files) (and $root.Values.secrets.enabled $root.Values.secrets.files) }}
          volumeMounts:
            {{- if and $root.Values.config.enabled $root.Values.config.files }}
            {{- range $file := $root.Values.config.files }}
            {{- $san := regexReplaceAll "[^a-zA-Z0-9-]" $file.name "-" }}
            - name: {{ printf "%s-%s-config-vol" (include "mychart.fullname" $root) $san | lower }}
              mountPath: {{ $file.mountPath }}
              subPath: {{ $file.name }}
              readOnly: true
            {{- end }}
            {{- end }}

            {{- if and $root.Values.secrets.enabled $root.Values.secrets.files }}
            {{- range $file := $root.Values.secrets.files }}
            {{- $san := regexReplaceAll "[^a-zA-Z0-9-]" $file.name "-" }}
            - name: {{ printf "%s-%s-secret-vol" (include "mychart.fullname" $root) $san | lower }}
              mountPath: {{ $file.mountPath }}
              subPath: {{ $file.name }}
              readOnly: true
            {{- end }}
            {{- end }}
          {{- end }}

      volumes:
        {{- if and $root.Values.config.enabled $root.Values.config.files }}
        {{- range $file := $root.Values.config.files }}
        {{- $san := regexReplaceAll "[^a-zA-Z0-9-]" $file.name "-" }}
        - name: {{ printf "%s-%s-config-vol" (include "mychart.fullname" $root) $san | lower }}
          configMap:
            name: {{ printf "%s-%s" (include "mychart.fullname" $root) $san | lower }}
        {{- end }}
        {{- end }}

        {{- if and $root.Values.secrets.enabled $root.Values.secrets.files }}
        {{- range $file := $root.Values.secrets.files }}
        {{- $san := regexReplaceAll "[^a-zA-Z0-9-]" $file.name "-" }}
        - name: {{ printf "%s-%s-secret-vol" (include "mychart.fullname" $root) $san | lower }}
          secret:
            secretName: {{ printf "%s-%s" (include "mychart.fullname" $root) $san | lower }}
        {{- end }}
        {{- end }}
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 75
        - pause: { duration: 30s }
        - setWeight: 100
{{- end }}
