{{- $root := . -}}
{{- if .Values.secrets.enabled }}
{{- range $file := $root.Values.secrets.files }}
  {{- $fname := $file.name }}
  {{- $san := regexReplaceAll "[^a-zA-Z0-9-]" $fname "-" }}
  {{- $sname := printf "%s-%s" (include "mychart.fullname" $root) $san | lower }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $sname }}
  labels:
    {{- include "mychart.labels" $root | nindent 4 }}
type: Opaque
data:
  {{ $fname }}: {{ ( $root.Files.Get (printf "files/secrets/%s" $fname) ) | b64enc }}
---
{{- end }}

{{- if $root.Values.secrets.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.fullname" $root }}-default
  labels:
    {{- include "mychart.labels" $root | nindent 4 }}
type: Opaque
data:
{{- range $k, $v := $root.Values.secrets.data }}
  {{ $k }}: {{ $v | b64enc }}
{{- end }}
{{- end }}
{{- end }}
